### ISSUE TITLE
Type-checking files with loooong lines makes emacs unresponsive

### ISSUE THREAD

**Issue by mads379** [the-lambda-church/merlin#341]
Hi there,

It's a bit embarrassing, I know, but I have an OCaml file that contains a string literal that contains 1250 chars. When I try to type-check this file emacs becomes unresponsive.

To reproduce create a file with the following content and type-check it in emacs using merlin.

```
let way_too_long_line = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
```

Some information about my setup.

```
emacs --version
GNU Emacs 24.4.1
```

```
opam switch
system  C system  System compiler (4.02.1)
```

```
opam info merlin
             package: merlin
             version: 2.0.0
          repository: default
        upstream-url: https://github.com/the-lambda-church/merlin/archive/v2.0.tar.gz
       upstream-kind: http
   upstream-checksum: a96465f2b0ed3364ffc1be66dd35961d
             depends: ocamlfind & yojson
   installed-version: 2.0.0 [system]
  available-versions: 1.3, 1.3.1, 1.3.1-trunk, 1.4, 1.4.1, 1.5, 1.6, 1.7, 1.7.1, 2.0.0
         description: Editor helper, provides completion, typing and sources browsing in Vim and Emacs
```

**Comment by def-lkb** [comment]
Strange, I have no problem here BUT we fixed recently a race condition in emacs mode which might explain this.
Can you try with the git version (release planned soon… maybe tomorrow, it will be nice to know if your issue is indeed fixed before :)) ?

Try: (you might need to remove merlin first, I don't remember the exact flags for opam :P)
```
$ opam pin merlin add https://github.com/the-lambda-church/merlin
$ opam install merlin 
```

**Comment by mads379** [comment]
`opam pin add merlin https://github.com/the-lambda-church/merlin` and opam took care of doing the reinstall :)

I still have the same issue with the pinned version though. I would be great to have another OS X Emacs user give it a try to see if my setup is broken somehow. I'll see if I can find someone to give it a go

**Comment by def-lkb** [comment]
I found an OS X install and it is immediately reproducible… I'll investigate.

**Comment by mads379** [comment]
Awesome, thanks!

**Comment by def-lkb** [comment]
Emacs handling of PTY on OSX stop sending input if there is no '\n' for more than 1024 characters.
Switching to pipe.

**Comment by mads379** [comment]
That did the trick. Thanks!
